/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as CounterIndexRouteImport } from './routes/counter/index'
import { Route as LibraryIdRouteImport } from './routes/library/$id'

const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterIndexRoute = CounterIndexRouteImport.update({
  id: '/counter/',
  path: '/counter/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/library/$id': typeof LibraryIdRoute
  '/counter': typeof CounterIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/library/$id': typeof LibraryIdRoute
  '/counter': typeof CounterIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/library/$id': typeof LibraryIdRoute
  '/counter/': typeof CounterIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/library/$id' | '/counter' | '/library'
  fileRoutesByTo: FileRoutesByTo
  to: '/library/$id' | '/counter' | '/library'
  id: '__root__' | '/library/$id' | '/counter/' | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
  CounterIndexRoute: typeof CounterIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter/': {
      id: '/counter/'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
  CounterIndexRoute: CounterIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
